apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: circuit
  namespace: default
spec:
  hosts: ["<DOMAIN>"]
  gateways: [ "gateway-app" ]
  http:
    - match:
      - uri:
          exact: "/circuit"
      redirect:
        uri: "/circuit/"
    - match:
      - uri:
          prefix: "/circuit/"
      rewrite:
        uri: "/"
      route:
        - destination:
            host: circuit

